# Generated by Django 6.1.1 on 2026-10-02 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='mpr',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='vendor',
        ),
        migrations.DeleteModel(
            name='MPR',
        ),
        migrations.DeleteModel(
            name='PurchaseOrder',
        ),
        migrations.DeleteModel(
            name='Vendor',
        ),
    ]
