# Generated by Django 6.1.1 on 2026-10-02 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_purchaseorder_mpr_remove_purchaseorder_vendor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermoduleright',
            name='can_view_mpr_entry',
        ),
        migrations.RemoveField(
            model_name='usermoduleright',
            name='can_view_mpr_report',
        ),
        migrations.RemoveField(
            model_name='usermoduleright',
            name='can_view_po_entry',
        ),
        migrations.RemoveField(
            model_name='usermoduleright',
            name='can_view_po_report',
        ),
    ]
