# Generated by Django 6.1.1 on 2026-09-30 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_code', models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                ('vendor_name', models.CharField(max_length=150)),
            ],
        ),
    ]
