# Generated by Django 6.1.1 on 2026-09-30 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='company_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
