# Generated by Django 6.1.1 on 2026-10-02 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0003_vendor_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='phone_number',
            field=models.CharField(default='03000000000', max_length=20),
            preserve_default=False,
        ),
    ]
