# Generated by Django 6.1.1 on 2026-10-03 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0007_vendor_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='company_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='company_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
