# Generated by Django 6.1.1 on 2026-10-05 14:41

from django.db import migrations, models


def populate_country_codes(apps, schema_editor):
    Country = apps.get_model("setup", "Country")
    for country in Country.objects.filter(country_code__isnull=True).iterator():
        Country.objects.filter(pk=country.pk).update(country_code=f"CTR{country.pk:05d}")


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0011_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='country_code',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
        migrations.RunPython(populate_country_codes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='country',
            name='country_code',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
