# Generated by Django 6.1.1 on 2026-10-06 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0012_country_country_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='country_code',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
